// Writes out/sw.js after the export, listing every file to precache so the
// site works with no network at all.
//
// The version is a hash of that list, so a deploy that changes anything gets a
// new cache and the old one is deleted; a deploy that changes nothing does not
// make anybody download the site again.
//
//   bun run scripts/serviceWorker.ts
import { createHash } from "node:crypto";
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const OUT = "out";

// WebLLM is several megabytes and only fetched if a student asks for offline
// marking. Precaching it would make every first visit pay for a feature almost
// nobody uses.
const TOO_BIG = 1_500_000;

function walk(dir: string, acc: string[] = []): string[] {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) walk(full, acc);
    else acc.push(full);
  }
  return acc;
}

const files = walk(OUT)
  .filter((f) => !f.endsWith(".map") && !f.endsWith("sw.js"))
  .filter((f) => statSync(f).size < TOO_BIG)
  .map((f) => `/${relative(OUT, f).split("\\").join("/")}`)
  .sort();

const hash = createHash("sha1");
for (const f of files) hash.update(f).update(String(statSync(join(OUT, f.slice(1))).size));
const version = hash.digest("hex").slice(0, 12);

const sw = `// Generated by scripts/serviceWorker.ts — do not edit.
const VERSION = ${JSON.stringify(version)};
const CACHE = "ibcshl-" + VERSION;
const FILES = ${JSON.stringify(files)};

// Take a complete copy of the site on first visit, so every later visit is
// served from disc and works with no network.
self.addEventListener("install", (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE);
      // In batches: a few hundred parallel requests makes the first load
      // fight with the page for bandwidth.
      for (let i = 0; i < FILES.length; i += 24) {
        await cache.addAll(FILES.slice(i, i + 24)).catch(() => {});
      }
      await self.skipWaiting();
    })(),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      for (const name of await caches.keys()) {
        if (name.startsWith("ibcshl-") && name !== CACHE) await caches.delete(name);
      }
      await self.clients.claim();
    })(),
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return; // CDN and API traffic pass through

  event.respondWith(
    (async () => {
      // Hashed assets can never change under a given name, so the cache is
      // always right and the network is never consulted.
      const cached = await caches.match(request, { ignoreSearch: true });
      if (cached && url.pathname.startsWith("/_next/static/")) return cached;

      try {
        const fresh = await fetch(request);
        if (fresh.ok) {
          const cache = await caches.open(CACHE);
          cache.put(request, fresh.clone());
        }
        return fresh;
      } catch {
        // Offline: the cached copy, or the page shell for a navigation.
        if (cached) return cached;
        if (request.mode === "navigate") {
          const shell = await caches.match("/index.html");
          if (shell) return shell;
        }
        return new Response("Offline, and this page was never cached.", {
          status: 503,
          headers: { "Content-Type": "text/plain" },
        });
      }
    })(),
  );
});
`;

writeFileSync(join(OUT, "sw.js"), sw);
const bytes = files.reduce((n, f) => n + statSync(join(OUT, f.slice(1))).size, 0);
console.log(
  `wrote out/sw.js — ${files.length} files, ${(bytes / 1024 / 1024).toFixed(1)} MB precached, version ${version}`,
);
